fix: Update puppeteer-14 Dockerfile
googleapis/testing-infra-docker pull request #280
Opened 2023-03-03 17:39 UTC by kweinmeister

Moving the Cloud SDK installation below setting the user.

This should hopefully address:
```
ERROR: (gcloud.components.update) You cannot perform this action because you do not have permission to modify the Google Cloud SDK installation directory [/home/node/google-cloud-sdk].
```

2023-03-06 20:11 UTC, sofisl commented
I think we should close this, and instead remove lines 89 & 90 here: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/main/.kokoro/build-with-run.sh#L89

2023-03-06 22:38 UTC, sofisl requested changes
Please revert changes to node/14-puppeteer/Dockerfile

2023-03-06 23:20 UTC, kweinmeister commented
> Please revert changes to node/14-puppeteer/Dockerfile

Done

2023-03-07 03:13 UTC, sofisl approved these changes

2023-03-07 03:14 UTC, merged