optimization debian package manager tweaks
googleapis/testing-infra-docker pull request #56
Opened 2020-03-06 21:51 UTC by Rajpratik71

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

Signed-off-by: Pratik Raj <rajpratik71@gmail.com>

2020-03-09 16:19 UTC, Rajpratik71 commented
@blowmage @lukesneeringer @dazuma @jskeet  requesting review

2020-03-09 16:41 UTC, jskeet commented
This isn't a repository I have any experience with. I defer to those who use it.

2020-06-13 15:55 UTC, Rajpratik71 commented
@busunkim96 requesting review

2020-06-15 17:26 UTC, busunkim96 approved these changes
@dazuma @chingor13 @bcoe @codyoss 

Could you confirm that the changes are OK for your language?

(If the images here aren't being used, please let me know and we can remove them to avoid confusion.)

2020-06-15 17:44 UTC, codyoss commented
Go does not currently use this repository to manage its docker images used for builds(although maybe it should in the future). I defer to others.

2020-06-15 18:02 UTC, dazuma requested changes
Ruby's usage here is complicated, because there are two sources of these images (one here and the other in googleapis/google-cloud-ruby) and they compete with each other and can clobber each other. We need to clean that up, but in the meantime, please do not make any changes to any of the Ruby images in this repo, to prevent this repo from building Ruby images. If you want to make this change to the Ruby images, do so in https://github.com/googleapis/google-cloud-ruby/tree/master/.kokoro/docker instead.

2020-06-15 18:44 UTC, Rajpratik71 commented
> Ruby's usage here is complicated, because there are two sources of these images (one here and the other in googleapis/google-cloud-ruby) and they compete with each other and can clobber each other. We need to clean that up, but in the meantime, please do not make any changes to any of the Ruby images in this repo, to prevent this repo from building Ruby images. If you want to make this change to the Ruby images, do so in https://github.com/googleapis/google-cloud-ruby/tree/master/.kokoro/docker instead.

done as requested

2020-06-15 19:35 UTC, dazuma approved these changes

2020-06-15 19:35 UTC, dazuma commented
Thanks!

2020-06-16 00:12 UTC, bcoe approved these changes

2020-07-06 15:16 UTC, dazuma submitted a review, later dismissed

2020-07-06 15:16 UTC, dazuma commented on node/8-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends wget --no-install-recommends \
Extra `--no-install-recommends`

2020-07-06 15:16 UTC, dazuma commented on node/8-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommendsq libgconf-2-4
Bad copy-paste

2020-07-06 15:16 UTC, dazuma commented on node/12-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends wget --no-install-recommends \
Extra `--no-install-recommends`

2020-07-06 15:16 UTC, dazuma commented on node/12-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommendsq libgconf-2-4
Bad copy-paste

2020-07-06 16:33 UTC, Rajpratik71 commented on node/8-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends wget --no-install-recommends \
fixed

2020-07-06 16:33 UTC, Rajpratik71 commented on node/8-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommendsq libgconf-2-4
fixed

2020-07-06 16:33 UTC, Rajpratik71 commented on node/12-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommends wget --no-install-recommends \
fixed

2020-07-06 16:33 UTC, Rajpratik71 commented on node/12-puppeteer/Dockerfile
> +RUN apt-get update && apt-get install -y --no-install-recommendsq libgconf-2-4
fixed

2020-08-19 03:28 UTC, JustinBeckwith commented
@chingor13 - can I trouble you to give this one a review and decide if it's a change we want?

2020-08-19 18:47 UTC, chingor13 approved these changes
This looks fine to me.

2021-06-17 02:50 UTC, parthea commented
Hi @Rajpratik71 , Please could you resolve conflicts ?

2021-06-19 11:01 UTC, parthea approved these changes

2021-06-19 11:04 UTC, parthea commented
/gcbrun

2021-06-19 11:09 UTC, parthea commented
@Rajpratik71 The `conventionalcommits.org` check is failing. Please can you take a look? Changing the commit message to `chore: optimization debian package manager tweaks` may resolve the issue.

2021-06-19 15:03 UTC, Rajpratik71 commented
> @Rajpratik71 The `conventionalcommits.org` check is failing. Please can you take a look? Changing the commit message to `chore: optimization debian package manager tweaks` may resolve the issue.

@parthea  done as required

2021-06-19 20:33 UTC, parthea commented
/gcbrun

2021-06-25 21:55 UTC, bcoe approved these changes

2021-06-25 22:04 UTC, tmatsuo commented
So are we pushing docker images for testing without knowing our tests would pass or not?
I would say this again and again. This is a recipe for disaster :(

2021-07-03 12:02 UTC, parthea commented
I'm going to close this PR as there is potential risk that downstream tests will fail and the risk is not worth the benefit of smaller downloads.

2021-07-03 12:02 UTC, closed without merging